services:
  - type: web
    name: harshini-portfolio-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GITHUB_USERNAME
        value: Harshini-BS
      - key: GITHUB_TOKEN
        sync: false